version: "3.8"

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  server:
    build: ./discovery-server
    restart: on-failure
    env_file: ./.env
    ports:
      # - $SPRING_LOCAL_PORT_SERVER:$SPRING_DOCKER_PORT_SERVER
      - "8761:8761"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name":"eureka-server",
        "eureka.client.register-with-eureka":"false",
        "eureka.client.fetch-registry":"false",
        "logging.level.com.netflix.eureka":"off",
        "logging.level.com.netflix.discovery":"off"
      }'
    stdin_open: true
    tty: true

  task:
    depends_on:
      - mysqldb
      - server
    build: ./tms
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    links:
      - server
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "eureka.client.serviceUrl.defaultZone": "http://server:8761/eureka/"
      }'
    stdin_open: true
    tty: true

  user:
    depends_on:
      - mysqldb
      - server
    build: ./user
    restart: on-failure
    env_file: ./.env
    ports:
      - "8090:8090"
    links:
      - server
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "eureka.client.serviceUrl.defaultZone": "http://server:8761/eureka/"
      }'
    stdin_open: true
    tty: true

  user2:
    depends_on:
      - mysqldb
      - server
    build: ./user
    restart: on-failure
    env_file: ./.env
    ports:
      - "8091:8091"
    links:
      - server
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "eureka.client.serviceUrl.defaultZone": "http://server:8761/eureka/"
      }'
    stdin_open: true
    tty: true

  gateway:
    build: ./api-gateway
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT_GATEWAY:$SPRING_DOCKER_PORT_GATEWAY
    links:
      - server
    environment:
      SPRING_APPLICATION_JSON: '{
            "eureka.client.serviceUrl.defaultZone": "http://server:8761/eureka/"
          }'
    stdin_open: true
    tty: true

  reverse-proxy:
    image: nginx:1.17.10
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:8084"

volumes:
  db:

