server:
  port: 8085

#eureka:
#  client:
#    service-url:
#      defaultZone: http://server:8761/eureka

spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: TASK-SERVICE
          uri:
            lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**

        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: TASK-SERVICE
          uri:
            lb://TASK-SERVICE
          predicates:
            - Path=/specialTasks/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT